Resources:
  StartContinuousAssessmentLambdaRole: 
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          - 
            Action: 
              - "sts:AssumeRole"
            Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/AmazonInspectorFullAccess"
      Path: /
      Policies: 
        - 
          PolicyDocument: 
            Statement: 
              - 
                Action: 
                  - "ssm:GetParameter"
                  - "ec2:DescribeImages"
                  - "ec2:RunInstances"
                  - "ec2:CreateTags"
                Effect: Allow
                Resource: "*"
                Sid: StartContinuousAssessmentLambdaPolicyStmt
            Version: "2012-10-17"
          PolicyName: root
    Type: "AWS::IAM::Role"
  AnalyzeInspectorFindingsLambdaRole: 
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          - 
            Action: 
              - "sts:AssumeRole"
            Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Path: /
      Policies: 
        - 
          PolicyDocument: 
            Statement: 
              - 
                Action: 
                  - "sns:Publish"
                  - "ec2:DescribeInstances"
                  - "ec2:TerminateInstances"
                  - "inspector:AddAttributesToFindings"
                  - "inspector:DescribeFindings"
                  - "inspector:ListFindings"
                Effect: Allow
                Resource: "*"
                Sid: AnalyzeInspectorFindingsLambdaPolicyStmt
            Version: "2012-10-17"
          PolicyName: AnalyzeInspectorFindingsLambdaPolicy
    Type: "AWS::IAM::Role"